config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # As a user, I can list tasks # Read
  get 'tasks', to: 'tasks#index'

  # As a user, I can add a new task #Create
  get 'tasks/new', to: 'tasks#new' #display form

  #  As a user, I can view the details of a task when clicking on the link - read
  get 'tasks/:id', to: 'tasks#show', as: :task_details

  # As a user, I can add a new task #Create
  post 'tasks', to: 'tasks#create'

  # As a user, I can edit a task
  # show edit form
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task

  # update the task
  patch 'tasks/:id', to: 'tasks#update'
  # patch is when the file already exists but it is being edited

  # delete task
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    # redirecting to show page
    redirect_to task_details_path(@task) # @task.id
  end

  def edit

  end

  def update
    @task.update(task_params)
    # redirecting to show page
    redirect_to task_details_path(@task)
  end

  def destroy
    @task.destroy
    # can't redirect to show 'cause it does not exists anymore, then:
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<!-- in partials we don't use instance variables, so task -->
<%= form_for task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%= f.submit %>

<% end %>

app/views/tasks/edit.html.erb
<h1>Edit task:</h1>


<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>Tasks:</h1>

<!-- We have an array with all tasks -->
<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= link_to task.title, task_details_path(task)%>
      <!-- task_details_path(task) this prefix was given by me on show on route -->
    </li>
  <% end %>
</ul>

<%= link_to '📌Create new task', tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Add a new task:</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>Task Details</h1>

<p>Task: <%= @task.title %> </p>
<p>Details: <%= @task.details %></p>
<p>Completed: <%= @task.completed %></p>

<!--  link below should redirect to destroy on controller -->
<%= link_to '📝Edit task', edit_task_path(@task)%>
<br>
<%= link_to '❌Remove task', tasks_path, method: :delete %>
<br>
<%= link_to "⬅️Back to list", tasks_path %>